version: '3.8'

services:
  api:
    build: .
    container_name: my-python-app
    ports:
      - "0.0.0.0:8501:8501"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    # Optional: Add resource limits to prevent container from using too much memory
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

networks:
  app-network:
    driver: bridge
